### ISSUE TITLE
Don't assume './' when loading the cssLint config

### ISSUE THREAD

**Issue by mike-engel** [lazd/gulp-csslint#13]
If you use the `--cwd` flag in the gulp cli, it can cause some headaches/confusion. Should allow for absolute paths. Assuming the cssLint config is in the current directory potentially leads to stuff like this:

```javascript
module.exports = gulp.task( 'css', function() {
    'use strict';

    return gulp.src( src.lib + 'less/' + src.project + '.less' )
        .pipe( less())
        .pipe( csslint( '../../../../.csslintrc' ))
        .pipe( csslint.reporter())
        .pipe( gulp.dest( cwd + 'lib/css/' ));
});
```

**Comment by SimenB** [comment]
I failed trying to close this from the commit...

**Comment by lazd** [comment]
@SimenB ha! No biggie, the PR is referenced :)
