### ISSUE TITLE
Mismatch npmjs.com README and repo README

### ISSUE THREAD

**Issue by SimenB** [lazd/gulp-csslint#16]
Amongst other things, the failure-reporter is not mentioned on [npmjs.com](https://www.npmjs.com/package/gulp-csslint).

**Comment by SimenB** [comment]
There are a few features merged now that'll probably get an `npm publish` soon. So this "reminder"-issue shouldn't be needed

**Comment by lazd** [comment]
Yup, sounds like a plan. I'll work to merge everything you've sent today!
