### ISSUE TITLE
Add rules to csslint

### ISSUE THREAD

**Issue by lukasoppermann** [lazd/gulp-csslint#24]
Hey,

since csslint has a possibility to add rules, it would be awesome if this ability would also be added to this gulp plugin.

**Comment by lazd** [comment]
I think we could support this by exposing the CSSLint module as required by `gulp-csslint`. Then you'll have access to its `addRule` method. PRs welcome, it's a simple change, wanna give it a shot?

**Comment by lukasoppermann** [comment]
Sorry, I have no idea how to do that, so I can not sent a PR. I am happy to test it, if you would do it though. :)

**Comment by lorenz068** [comment]
I just do a npm install --save-dev gulp-csslint but i can access of the addRule method. 
Is NPM up to date?
Thank for your job man!

**Comment by lazd** [comment]
@lorenz068 this feature hasn't been published yet. I'm planning on releasing later today, will update this thread when it's published!

**Comment by lorenz068** [comment]
Nice :) Thank you!

2015-04-30 17:20 GMT-04:00 Larry Davis <notifications@github.com>:

**Comment by lorenz068** [comment]
Do you have the chance to publish a release?

**Comment by lazd** [comment]
@lorenz068 I actually didn't get to it. I'll do so soon, and will hopefully have another contributor on the project soon so I'm not a bottleneck for things like this!

**Comment by lukasoppermann** [comment]
Is it merged already? It would be really awesome if you could merge it.

**Comment by aarr0n** [comment]
:+1: for this! :

**Comment by lorenz068** [comment]
+1

**Comment by lazd** [comment]
My apologies for being slow to release this, I was in the middle of a big release at work and it took precedence. I'll get to it soon, and will be adding @lukasoppermann as a contributor/package owner so releases can happen faster!

**Comment by lazd** [comment]
Released as `gulp-csslint@0.2.0`!

**Comment by lukasoppermann** [comment]
Yeaaay. :+1:
