### ISSUE TITLE
Lint fails on empty CSS file

### ISSUE THREAD

**Issue by igorshubovych** [lazd/gulp-csslint#30]
This issue is a duplicate of #5. I cannot reopen it, but I think it is very important.

In some development processes it is convenient to have empty files, e.g. when you have one JS and CSS file per page, and they can be empty at the moment because they do not override defaults. However in this case it is very inconvenient that CSS linting fails.

The original ticket was open on Apr 9, 2014. Today is July 10, 2015. More than a year come since initial report.
https://github.com/CSSLint/csslint/pull/463 is still open. I do not think we should rely on it. I think it is better to patch gulp-csslint. It will continue working anyway after CSS Lint fixes it.

**Comment by igorshubovych** [comment]
Will it help to resolve the issue if I provide a Pull Request?

**Comment by SimenB** [comment]
@igorshubovych #32

**Comment by igorshubovych** [comment]
Awesome. Thanks a lot.

**Comment by igorshubovych** [comment]
Wait, this is not merged to master yet, right?

**Comment by SimenB** [comment]
Not merged, no

On Wed, 22 Jul 2015 at 15:33 Igor Shubovych <notifications@github.com>
wrote:

> Reopened #30 <https://github.com/lazd/gulp-csslint/issues/30>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lazd/gulp-csslint/issues/30#event-362279567>.
>
-- 

--
Simen Bekkhus

**Comment by igorshubovych** [comment]
As it is merged, I think the issue can be closed, right?

**Comment by lazd** [comment]
Merged, but not released yet.
