### ISSUE TITLE
Publish new release to npm

### ISSUE THREAD

**Issue by 0xazure** [lazd/gulp-csslint#33]
The last release for `gulp-csslint` was over a year ago.  There have been [a lot of great features added](https://github.com/lazd/gulp-csslint/compare/v0.1.5...master) in that timeframe, but we can't make use of them in our projects yet :disappointed:.

[I see I'm not the only one](https://github.com/lazd/gulp-csslint/pull/25#issuecomment-128337907) looking for a new release.

**Comment by lazd** [comment]
`gulp-csslint@0.2.0` has been published to npm!

**Comment by 0xazure** [comment]
Thank you so much. ✨
