### ISSUE TITLE
Disabling a rule via inline comment disables it for all following files

### ISSUE THREAD

**Issue by betaorbust** [lazd/gulp-csslint#41]
cssLintPlugin defines a global ruleset object with all available rules.

Inside the returned through.obj, rules for the file are matched up and if any are false, it deletes them from the global `ruleset` object. All following files loop over the keys in `ruleset` and, now missing the previously disabled key, don't process it.

Basically, once you turn a rule off in one context, it's turned off in all following contexts.

**Comment by betaorbust** [comment]
Update. On looking further into this, it appears that any time you use an inline `/*csslint duplicate-properties:false*/` (or any other rule) all files linted after that will have that rule disabled. So in a large codebase with various inline overrides, by the time you're linting the last files, basically no rules will be running.

**Comment by lazd** [comment]
Bah! That makes sense. If we shut a rule off on a per-file basis, we shouldn't be affecting the ruleset for the rest of the files.

How about the opposite? If we turn a rule on for a single file, it shouldn't be added to the ruleset for the rest of the files.
