### ISSUE TITLE
TypeError: gulp.files is not a function

### ISSUE THREAD

**Issue by StephenBugden** [lazd/gulp-csslint#46]
Hello,

I am trying to run the code below to validate some css and write the results to a file. I took the code from and modified it to use my directories:
https://www.npmjs.com/package/gulp-csslint

I'm getting an error with the following message:
TypeError: gulp.files is not a function

Here's the code:
//************************************************
var gulp = require('gulp');

var CSS_PATH = 'public/css/**/*.css';
var DIST_PATH = 'public/dist';

gulp.task('lintcss', function(cb) {
  var fs = require('fs');
  var output = '';
 
  gulp.files(CSS_PATH)
    .pipe(csslint())
    .pipe(csslint.reporter('junit-xml', {logger: function(str) { output += str; }}));
 
  fs.writeFile(DIST_PATH + 'junit.xml', output, cb);
});
//*****************************************************

Best Regards,

Steve

**Comment by lazd** [comment]
The docs seem to have an error, it should be `gulp.src`, not `gulp.files`. I've updated the docs, thanks!

**Comment by StephenBugden** [comment]
Hi Larry,

Thank you for your reply.

I tried all sorts of things, that was one of them it just gives me a blank
file even though I put errors in my css. There must be something else that
needs to change.

Steve
