### ISSUE TITLE
Error writing report to XML file

### ISSUE THREAD

**Issue by StephenBugden** [lazd/gulp-csslint#47]
Hello,

I posted a question a couple of days ago, but can see that it's now closed:
https://github.com/lazd/gulp-csslint/issues/46

I changed my code according to the suggestion there, it now reads:
Here's the code:
```js
var gulp = require('gulp');

var CSS_PATH = 'public/css/*/.css';
var DIST_PATH = 'public/dist';

gulp.task('lintcss', function(cb) {
  var fs = require('fs');
  var output = '';
 
gulp.src(CSS_PATH)
.pipe(csslint())
    .pipe(csslint.reporter('junit-xml', {logger: function(str) { output += str; }}));
 
  fs.writeFile(DIST_PATH + 'junit.xml', output, cb);
});
```

But i now get an error 'Error: Invalid reporter'

I took the code original from:
https://www.npmjs.com/package/gulp-csslint
But obviously something still isn't right.

All I really want to do is to output the report as xml to a file.

Best Regards,

Steve

**Comment by Ryuno-Ki** [comment]
@StephenBugden I'd very grateful if you could use [code fences](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

The following worked for me (albeit being ugly as hell):
http://stackoverflow.com/a/28122171

```javascript
/*global require*/
var gulp = require('gulp'),
    fs = require('fs'),
    process = require('process'),
    csslint = require('gulp-csslint');

gulp.task('csslint', function(callback) {
    'use strict';
    var file;

    file = 'reports/csslint.xml';

    // Clear old content
    fs.writeFileSync(file, '');

    process.stdout.write = function(chunk) {
        fs.appendFile(file, chunk);
    };

    gulp.src('src/css/*.css')
      .pipe(csslint('./.csslinrc.json'))
      .pipe(csslint.reporter('checkstyle-xml'));
});
```

You are basically monkeypatching `process.stdout.write` to behave like you want, since the `output` variable remains empty after the `gulp.pipe` finished (albeit it grew by appending `str`s).

Oh, and your path to file is probably wrong:
`DIST_PATH = 'public/dist'` + `'junit.xml'` = ''public/distjunit.xml'` (missing slash).

**Comment by lazd** [comment]
@SimenB any thoughts here? Seems like this should be easier than @Ryuno-Ki's solution.

**Comment by StephenBugden** [comment]
@Ryuno-Ki Thank you for your reply and the tip on the file path.

With some help, I created a custom reporter. I haven't included xml tags but it's trivial to put them in. Here's the code (with code fences as requested :-)

```

var gulp = require('gulp');
var csslint = require('gulp-csslint');
//path for css files to be validated
var CSS_PATH = 'public/css/**/*.css';

var customReporter = function(file) 
{
  var Msg = "";
  Msg += file.csslint.errorCount + " errors in " + file.path + "\r\n";
  
  file.csslint.results.forEach(function(result) {
    Msg += result.error.message  + " on line "  + result.error.line + "\r\n";
  });
  
  require('fs').appendFileSync('cssErrors.txt', Msg); 
};

gulp.task('csslint', function() 
{		
  //Clear the file out if it exists
  require('fs').writeFileSync('cssErrors.txt', '');
	
  gulp.src(CSS_PATH)
    .pipe(csslint())
    .pipe(csslint.reporter(customReporter));
});

```

**Comment by SimenB** [comment]
Try

```js
gulp.task('lintcss', cb => {
  var fs = require('fs');
  var output = '';

  gulp.src(CSS_PATH)
    .pipe(csslint())
    .pipe(csslint.reporter('junit-xml', { logger: str => { output += str; } }))
    .on('end', err => {
      if (err) return cb(err);

      fs.writeFile(DIST_PATH + 'junit.xml', output, cb);
    });
});
```

If it works, the example should be updated.

(difference vs current example is that the current one is synchronous)

**Comment by StephenBugden** [comment]
@SimenB Thank you for the reply. 

I just tried it, completed without errors but no file written out unfortunately.

ps I changed the line to write the file out to have a forward slash before the filename

```js
fs.writeFile(DIST_PATH + '/junit.xml', output, cb);                                         
```

**Comment by SimenB** [comment]
Do you have a sample project?

**Comment by StephenBugden** [comment]
Trying to pull out the relevant bits, as it's all mixed up with a load of other stuff that i was trying.

**Comment by SimenB** [comment]
you can try just 

```js
var path = require('path');

// ...

fs.writeFile(path.join(__dirname, 'dist', 'junit.xml', output, cb);
```

**Comment by StephenBugden** [comment]
Having trouble cutting out the relevant files keep getting an error copying -> file names are longer than supported by the system.

Will try the code in the last reply, thanks.

**Comment by StephenBugden** [comment]
Modified line to close the directory path i.e.
fs.writeFile(path.join(__dirname, 'dist'), 'junit.xml', output, cb);	

Still no file, unfortunately.

**Comment by SimenB** [comment]
Comma in wrong place

**Comment by StephenBugden** [comment]
OK thanks, tried:
fs.writeFile(path.join(__dirname, 'public/dist', 'junit.xml'), output, cb);

public/dist is the path relative to the gulpfile.js

**Comment by StephenBugden** [comment]
Still no file.

**Comment by Ryuno-Ki** [comment]
Move this:
`fs.writeFile(path.join(__dirname, 'dist'), 'junit.xml', output, cb);`
to
`fs.writeFile(path.join(__dirname, 'dist', 'junit.xml'), output, cb);`
(closing bracket in wrong place).

**Comment by StephenBugden** [comment]
@Ryuno-Ki Thanks, just tried, no difference unfortunately.

**Comment by StephenBugden** [comment]
Unable to copy the project, filenames too long. Can't create a zip either, presumably for the same reason.

**Comment by SimenB** [comment]
Can you try to console log some?

```
  gulp.src(CSS_PATH)
    .pipe(csslint())
    .pipe(csslint.reporter('junit-xml', { logger: str => { output += str; } }))
    .on('end', err => {
      if (err) return cb(err);
    
      console.log(output);

      fs.writeFile(path.join(__dirname, 'dist', 'junit.xml'), output, cb);
    });
```

**Comment by StephenBugden** [comment]
Still nothing I

**Comment by SimenB** [comment]
Then I'd use https://www.npmjs.com/package/gulp-debug to see if any files actually are in your stream

**Comment by StephenBugden** [comment]
I've installed the gulp debugger, so now I have:

```js

var gulp = require('gulp');
var csslint = require('gulp-csslint');
var debug = require('gulp-debug');

var CSS_PATH = 'public/css/**/*.css';

gulp.task('lintcss5', cb => {
  var fs = require('fs');
  var output = '';
  var path = require('path');

  gulp.src(CSS_PATH)
    .pipe(csslint())
	.pipe(debug({title: 'debug1:'}))
    .pipe(csslint.reporter('junit-xml', { logger: str => { output += str; } }))
	.pipe(debug({title: 'debug2:'}))
    .on('end', err => {
      if (err) return cb(err);
	   console.log(output);
      //fs.writeFile(DIST_PATH + '/junit.xml', output, cb);	  
      fs.writeFile(path.join(__dirname, 'public', 'dist', 'junit.xml'), output, cb);	  
    });
});
```


Output as follows:
![image](https://cloud.githubusercontent.com/assets/3857101/15142206/f38aedd6-169b-11e6-9cc1-95808d0158d7.png)

**Comment by Ryuno-Ki** [comment]
`.on('end', function(err) { /* … */ })` is never called on my machine.

```
$ npm --version
2.14.12
$ node --version
v4.3.2
$ gulp --version
CLI version 3.9.1
Local version 3.9.1
```
I'm working on a vagrant box running Ubuntu Trusty 64Bit . `gulp-csslint` is `^0.3.0`

**Comment by Ryuno-Ki** [comment]
```javascript
/*global require*/
var gulp = require('gulp'),
    fs = require('fs'),
    csslint = require('gulp-csslint');
var process;
try {
    process = require('process');
} catch (e) {
    /* Could not import process module! */
    process = null;
}

gulp.task('csslint', function(callback) {
    'use strict';
    var file;

    file = 'reports/csslint.xml';

    // Clear old content
    fs.writeFileSync(file, '');

    if (process != null) {
        process.stdout.write = function(chunk) {
            fs.appendFileSync(file, chunk);
        };

        gulp.src('src/css/*.css')
            .pipe(csslint('./.csslinrc.json'))
            .pipe(csslint.reporter('checkstyle-xml'));
    } else {
        /* Fallback */
        gulp.src('src/css/*.css')
            .pipe(csslint('./.csslinrc.json'))
            .pipe(csslint.reporter('checkstyle-xml', {
                logger: function(chunk) { fs.appendFileSync(file, chunk); }
        }));
    }
});
```

`fs.appendFileSync` is necessary, because the async flavour missed the leading/trailing `<?xml …?><checkstyle>` tag (that is, `startFormat()` and `endFormat()`).

**Comment by SimenB** [comment]
Hmm, it's not supposed to be that convoluted... Weird that `on('end')` isn't called

**Comment by StephenBugden** [comment]
@Ryuno-Ki  Thank you for the update, I've just tried it, but got an error.

![image](https://cloud.githubusercontent.com/assets/3857101/15150946/2a7a4bc2-16c7-11e6-98ea-2363f2783692.png)

No errors if i comment that line out:
//.pipe(csslint('./.csslintrc.json'))
What should the 'csslinrc.json' or even 'csslintrc.json' file contain?

With the above line commented out, there are no command line errors, and a csslint.xml file is created but contains no errors. I do have a few errors in my css just in case you're wondering :-)

**Comment by Ryuno-Ki** [comment]
@StephenBugden You're missing that file.

Look at [bootstrap's .csslintrc](https://github.com/twbs/bootstrap/blob/795d2208b882e194e6059a1639e056e020d64072/less/.csslintrc). I renamed it to `.csslintrc.json` to trigger syntax highlighting (and it needs to be valid JSON).

You can omit that line if you go for `.csslintrc`.

**Comment by StephenBugden** [comment]
@Ryuno-Ki Thank you for your reply.

I'm a bit confused to be honest. Do i need to have that reporting configuration file in place for the validation to work? I am assuming not and initially, I would be happy just to get something working. But if i omit the line for the reporting configuration file, an XML report is created but contains no errors.

If i do create an reporting configuration file, I found the definitions here:
[https://github.com/CSSLint/csslint/wiki/Rules-by-ID](url)
Then i presume I would create a json file with the same structure as the bootstrap .csslintrc you mentioned.

Also what does the last dot in './.' mean?
I relaise './'  means up one level, not sure what the extra '.' does.

I'm sorry to ask so many questions, gulp is very new to me and i found decent sources of information to get started are lacking, a certain level of knowledge is assumed.

Steve

**Comment by Ryuno-Ki** [comment]
The CSSLint docs state [a csslintrc file is optional](https://github.com/CSSLint/csslint/wiki/Command-line-interface#configuration-files). ("You _can_ also specify …").

The `console.log(chunk)` lines in this snippet should show, whether gulp-csslint detects any error (in case writing/appending to file fails).

```javascript
/*global require*/
var gulp = require('gulp'),
    fs = require('fs'),
    csslint = require('gulp-csslint');
var process;
try {
    process = require('process');
} catch (e) {
    /* Could not import process module! */
    process = null;
}

gulp.task('csslint', function(callback) {
    'use strict';
    var file;

    file = 'reports/csslint.xml';

    // Clear old content
    fs.writeFileSync(file, '');

    if (process != null) {
        process.stdout.write = function(chunk) {
            console.log(chunk);
            fs.appendFileSync(file, chunk);
        };

        gulp.src('src/css/*.css')
            .pipe(csslint('./.csslinrc.json'))
            .pipe(csslint.reporter('checkstyle-xml'));
    } else {
        /* Fallback */
        gulp.src('src/css/*.css')
            .pipe(csslint('./.csslinrc.json'))
            .pipe(csslint.reporter('checkstyle-xml', {
                logger: function(chunk) {
                    console.log(chunk);
                    fs.appendFileSync(file, chunk);
                }
        }));
    }
});
```

> Then i presume I would create a json file with the same structure as the bootstrap .csslintrc you mentioned.

Correctly. In case you [name it](https://github.com/lazd/gulp-csslint#ruleconfiguration) other than ".csslintrc" you'll need to tell the gulp-plugin, what the filename is.

`./.csslintrc.json`:
* `./` = Look in the current directory
* `.` for a hidden file (c. f. [dot file](https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory))
* `csslintrc.json` which is in JSON format

I'm new to gulp, too. But I gained knowledge with grunt and npm scripts before.

**Comment by SimenB** [comment]
@StephenBugden What does this print out?

```js
var gulp = require('gulp');
var csslint = require('gulp-csslint');
var debug = require('gulp-debug');

var CSS_PATH = 'public/css/**/*.css';

gulp.task('lintcss5', cb => {
  var fs = require('fs');
  var output = '';
  var path = require('path');

  gulp.src(CSS_PATH)
    .pipe(csslint())
    .pipe(debug({title: 'debug1:'}))
    .pipe(csslint.reporter('junit-xml', {
      logger: str => {
        console.log('arg for logger', str);
        output += str;
      }
    }))
    .pipe(debug({title: 'debug2:'}))
    .on('end', err => {
      if (err) return cb(err);
      console.log(output);
      // fs.writeFile(DIST_PATH + '/junit.xml', output, cb);
      fs.writeFile(path.join(__dirname, 'public', 'dist', 'junit.xml'), output, cb);
    });
});

```

**Comment by StephenBugden** [comment]
@SimenB Here's a screenshot of the output. No junit.xml file created.

![image](https://cloud.githubusercontent.com/assets/3857101/15179762/b12f74c2-1775-11e6-8f9e-b7238a1f2e5c.png)

**Comment by StephenBugden** [comment]
@Ryuno-Ki Thank you for your message. Going to try the code now.

**Comment by SimenB** [comment]
@StephenBugden 

Try `npm i SimenB/gulp-csslint#patch-1` and rerun the task from https://github.com/lazd/gulp-csslint/issues/47#issuecomment-218431130

**Comment by StephenBugden** [comment]
@Ryuno-Ki 


To suit my enviroment, I modified the code to:
```js
var fs = require('fs');
var csslint = require('gulp-csslint');


var process;
try {
    process = require('process');
} catch (e) {
    /* Could not import process module! */
    process = null;
}

gulp.task('csslint6', function(callback) {
    'use strict';
    var file;

    file = DIST_PATH + '/csslint.xml';

    // Clear old content
    fs.writeFileSync(file, '');

    if (process != null) {
        process.stdout.write = function(chunk) {
            console.log(chunk);
            fs.appendFileSync(file, chunk);
        };

        gulp.src(CSS_PATH)
            //.pipe(csslint('./.csslinrc.json'))
            .pipe(csslint.reporter('checkstyle-xml'));
    } else {
        /* Fallback */
        gulp.src(CSS_PATH)
            //.pipe(csslint('./.csslinrc.json'))
            .pipe(csslint.reporter('checkstyle-xml', {
                logger: function(chunk) {
                    console.log(chunk);
                    fs.appendFileSync(file, chunk);
                }
        }));
    }
});
```

The output is as follows:
![image](https://cloud.githubusercontent.com/assets/3857101/15180266/66bacfce-1778-11e6-9120-8232fa54652c.png)

An empty 'csslint.xml' file was created.

**Comment by SimenB** [comment]
You should never call `console.log` in `process.stdout.write` (you should also NEVER overwrite `process.stdout.write`, but that's another discussion) as `console.log` is implemented using `process.stdout.write` in node, so you created infinite recursion with the sample code provided

**Comment by StephenBugden** [comment]
@SimenB - Here's the output

![image](https://cloud.githubusercontent.com/assets/3857101/15180381/2ad3a854-1779-11e6-91c1-675e8e25547c.png)

**Comment by SimenB** [comment]
Oh, you don't have `git` available on the command line?

That's fine, just put the index file [here](https://github.com/SimenB/gulp-csslint/blob/patch-1/index.js) into `node_modules/gulp-csslint`

**Comment by StephenBugden** [comment]
@SimenB Tried putting the index.js file in but still get the same errors. Will put the original index.js file back.

How do i install git?
npm install git -g ??

**Comment by SimenB** [comment]
https://git-scm.com/

**Comment by StephenBugden** [comment]
@SimenB Installed Git, but still getting errors.

![image](https://cloud.githubusercontent.com/assets/3857101/15181204/c32dc810-177d-11e6-8e69-4a14a2aa5475.png)

**Comment by StephenBugden** [comment]
Sorry, please wait posted wrong screenshot.

**Comment by StephenBugden** [comment]
![image](https://cloud.githubusercontent.com/assets/3857101/15181273/38ed479c-177e-11e6-9c2b-eaa168be7721.png)

**Comment by SimenB** [comment]
Don't worry about the npm command, just install normal gulp-csslint and
replace the index file

On Wed, 11 May 2016, 14:41 StephenBugden, <notifications@github.com> wrote:

> Sorry, please wait posted wrong screenshot.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/lazd/gulp-csslint/issues/47#issuecomment-218447333>
>
-- 

--
Simen Bekkhus

**Comment by StephenBugden** [comment]
Still getting errors

**Comment by StephenBugden** [comment]
@SimenB - Sorry thought i had to rerun the patch. Reran the command and get the following:

Sample results below :-)


```xml
<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite time="0" tests="11" skipped="0" errors="11" failures="0" package="net.csslint" name="C:\Users\Steve\Google Drive\Inhouse\WebSites\DotNetNuke\Downloads\Gulp\UdemyGulpCourse\3\3\3-3-gulp-website\public\css\home - Copy.css"><testcase time="0" name="net.csslint.Requireuseofknownproperties"><error message="Unknown property 'backgdsfasdfround-color'."><![CDATA[8:2:	backgdsfasdfround-color:#f7f7f7;
]]></error></testcase><testcase time="0" name="net.csslint.Requireuseofknownproperties"><error message="Unknown property 'margin-bsdottom'."><![CDATA[13:2:	margin-bsdottom:3rem;	
]]></error></testcase><testcase time="0" name="net.csslint.ParsingErrors"><error message="Expected LBRACE at line 17, col 43."><![CDATA[17:43:	font-family: Helvetica, Arial, sans-serif;
]]></error></testcase><testcase time="0" name="net.csslint.ParsingErrors"><error message="Unexpected token ';' at line 17, col 43."><![CDATA[17:43:	font-family: Helvetica, Arial, sans-serif;
]]></error></testcase><testcase time="0" name="net.csslint.ParsingErrors"><error message="Expected LBRACE at line 18, col 15."><![CDATA[18:15:	font-weight: 300;
]]></error></testcase><testcase time="0" name="net.csslint.ParsingErrors"><error message="Unexpected token '300' at line 18, col 15."><![CDATA[18:15:	font-weight: 300;
]]></error></testcase><testcase time="0" name="net.csslint.ParsingErrors"><error message="Unexpected token ';' at line 18, col 18."><![CDATA[18:18:	font-weight: 300;
]]></error></testcase><testcase time="0" name="net.csslint.ParsingErrors"><error message="Expected LBRACE at line 19, col 16."><![CDATA[19:16:	margin-bottom:1.5rem;
]]></error></testcase><testcase time="0" name="net.csslint.ParsingErrors"><error message="Unexpected token '1.5rem' at line 19, col 16."><![CDATA[19:16:	margin-bottom:1.5rem;
]]></error></testcase><testcase time="0" name="net.csslint.ParsingErrors"><error message="Unexpected token ';' at line 19, col 22."><![CDATA[19:22:	margin-bottom:1.5rem;
]]></error></testcase><testcase time="0" name="net.csslint.ParsingErrors"><error message="Unexpected token '}' at line 20, col 1."><![CDATA[20:1:}]]></error></testcase></testsuite><testsuite time="0" tests="1" skipped="0" errors="1" failures="0" package="net.csslint" name="C:\Users\Steve\Google Drive\Inhouse\WebSites\DotNetNuke\Downloads\Gulp\UdemyGulpCourse\3\3\3-3-gulp-website\public\css\reset.css"><testcase time="0" name="net.csslint.Disallowuniversalselector"><error message="The universal selector (*) is known to be slow."><![CDATA[1:1:*
]]></error></testcase></testsuite></testsuites>
```

**Comment by SimenB** [comment]
So it worked?

**Comment by StephenBugden** [comment]
@SimenB - Yes!! Thank you.

**Comment by StephenBugden** [comment]
@SimenB - But what will happen now. Will you submit the modified index.js file for inclusion into csslint? Obviously i have a customised build at present.

**Comment by SimenB** [comment]
I will in a couple of minutes

**Comment by SimenB** [comment]
@StephenBugden #49

**Comment by StephenBugden** [comment]
@SimenB OK great.

btw. I think the documentation here needs to change:
https://www.npmjs.com/package/gulp-csslint
Under 'Reporter options'

Thank you for your help once again.

**Comment by StephenBugden** [comment]
@Ryuno-Ki Thank you for your help too.

**Comment by SimenB** [comment]
If you check the diff in teh PR, you can see that I also changed the docs

**Comment by StephenBugden** [comment]
@SimenB OK I can see the change, thanks.

How can i tell when it's released, by checking here?
https://github.com/lazd/gulp-csslint/releases

**Comment by SimenB** [comment]
It'll get there, but if you subscribe to the PR, you'll receive an email when @lazd says it's released.

Subscribe button looks like ![image](https://cloud.githubusercontent.com/assets/1404810/15182403/90fd3fb0-178c-11e6-9147-1630c505c3b5.png)

**Comment by StephenBugden** [comment]
SimenB OK great, thank you.

**Comment by Ryuno-Ki** [comment]
Got it. https://github.com/lazd/gulp-csslint/issues/47#issuecomment-218439676

Wasn't aware of it (I'm usually working on Front-End).

**Comment by lazd** [comment]
`gulp-csslint@0.3.1` has been released with the fix. Thanks @SimenB!
