### ISSUE TITLE
Lint fails if file is empty

### ISSUE THREAD

**Issue by hilios** [lazd/gulp-csslint#5]
In my project I compile the LESS to CSS and lint then, but occurs that I have a `variables.less` file that actually compiles into a empty css, leading to the error below:

``` sh
$ gulp lint:css
[gulp] 1 error found in /Users/hilios/Sites/engmonitor.com/static/less/layout/variables.css
[gulp] [GENERAL] Fatal error, cannot continue: Cannot call method 'getLine' of null undefined (undefined)
```

**Comment by igorshubovych** [comment]
Today is 2015 and this one is still not fixed.
Does it make sense to patch it here and then remove patch after/if CSSLint fixes it?
