### ISSUE TITLE
failReporter throws unhandled error

### ISSUE THREAD

**Issue by ovanderzee** [lazd/gulp-csslint#50]
When failReporter() is not used and csslint encounters an error, we see:

```
csslint: There are 1 problems in /file.css.

file.css
1: warning at line 9, col 5
Unknown property 'displ-ay'.
    displ-ay: none

```
That's good. But when failReporter(), or reporter('fail') is used we see:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: CSSLint failed for file.css
```

That is not graceful. Users don't understand it. It made me suspect problems in node, gulp, csslint.
It should end quietly, or only the message "Error: CSSLint failed for file.css"

setup:
gulp-csslint@0.3.0

gulp --version
CLI version 3.9.0
Local version 3.9.1

node --version
v5.11.1

npm --version
3.4.1

bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by lazd** [comment]
Hmm, maybe you want to include the default reporter before the fail reporter?

```
var csslint = require('gulp-csslint');

gulp.task('lint', function() {
  return gulp.src('lib/*.css')
    .pipe(csslint())
    .pipe(csslint.reporter()) // Display errors
    .pipe(csslint.reporter('fail')); // Fail on error (or csslint.failReporter())
});
```

This way, you still see the friendly error that shows what's actually wrong, and also fail.

That said, it's possible we're not failing the way gulp expects. If you don't mind testing `gulp-jshint` to see if it does the same with its [fail reporter](https://github.com/spalger/gulp-jshint#fail-reporter) and reporting back, then we can continue to investigate if changes are required.

Thanks!

**Comment by ovanderzee** [comment]
I did use the default reporter, i tested with gulp-jshint and it fails in the same way.
I made a branch "unhandled-error-event" in my project: https://github.com/ovanderzee/nl.ovdz.resource-router.
Maybe the oddity is I installed node with homebrew.

**Comment by ovanderzee** [comment]
I'm not seeing this anymore

**Comment by lazd** [comment]
Any insights on what you did to fix it? What does it do now?

**Comment by ovanderzee** [comment]
Now it shows what caused the error (like 
csslint: There are 1 problems  ..... Unknown property 'displ-ay'.
    displ-ay: none
)
and then gulp exits and we are back at the command line
As expected.

I turned my computer off and later on again instead of putting it to sleep. So, i think something in the background caused it.

**Comment by mickaelperrin** [comment]
This error is thrown mainly if you forgot the `return` statement before `gulp`.
