### ISSUE TITLE
Is there a way to ignore a specific error?

### ISSUE THREAD

**Issue by davemachado** [lazd/gulp-csslint#51]
Hello,

I am trying to see if there is a way to ignore a specific error while linting (i.e. "don't use IDs as selectors"). Is this possible with gulp-csslint? Thanks in advance!

**Comment by omahm** [comment]
It's in the documentation: [https://github.com/lazd/gulp-csslint#csslintcsslintrc](https://github.com/lazd/gulp-csslint#csslintcsslintrc)

Add your own file and set the warning/error/ignore level
