### ISSUE TITLE
`gulp-util` is deprecated

### ISSUE THREAD

**Issue by ladom** [lazd/gulp-csslint#61]
Hi, cause `gulp-util` is deprecated now, I tried to replace it according to [guidelines](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5). It works good and passes all tests. My repo is [here](https://github.com/ladom/gulp-csslint-1/tree/no-gulp-util).

**Comment by lazd** [comment]
Closed by #62, thanks!
